### ISSUE TITLE
What's the meaning of parameter `w` in function `p_mean_variance` ?

### ISSUE THREAD

**Issue by cuttle-fish-my** [a6o/3d-diffusion-pytorch#4]
Hi! I'm trying to reproduce the result from the original paper and I found out that the batch_size of the validation dataloader has been hard-coded to 128. Meanwhile, I noticed that the corresponding variable `w` has been hard-coded as:
```
 w = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7]).repeat(16)
```
Actually, I can not fully understand the meaning of this variable. From my observation, it seems that `w` controls how much difference between the prediction of the noise with and without conditions is added to the noise predicted with conditions.
However, I wonder why should we do that since I can't find any paper corresponding to that operation.

My question is: if I want to change the batch_size of validation from 128 to 1, what should I do about `w`? Can I just use the noise prediction only with conditions?

**Comment by a6o** [comment]
This is Classifier-free guidance weight. The paper uses either 2.0 or 3.0 as explained in the p21, section 7.3 (supplementary). 

The idea is to try different guidance weights and use the one that looks best to you.
